const Objectdata = [
    { id: 1, name: "Ali", age: 25 },
    { id: 2, name: "Sara", age: 22 },
    { id: 3, name: "Ahmed", age: 28 },
    { id: 4, name: "Ali", age: 25 },
    { id: 5, name: "Sara", age: 22 },
    { id: 6, name: "Ahmed", age: 28 },
    { id: 7, name: "Ali", age: 25 },
    { id: 8, name: "Sara", age: 22 },
    { id: 9, name: "Ahmed", age: 28 },
    { id: 10, name: "Ali", age: 25 },
    { id: 11, name: "Sara", age: 22 },
    { id: 12, name: "Ahmed", age: 28 },
    { id: 13, name: "Ali", age: 25 },
    { id: 14, name: "Sara", age: 22 },
    { id: 15, name: "Ahmed", age: 28 },
    { id: 1, name: "Ali", age: 25 },
    { id: 2, name: "Sara", age: 22 },
    { id: 3, name: "Ahmed", age: 28 },
    { id: 4, name: "Ali", age: 25 },
    { id: 5, name: "Sara", age: 22 },
    { id: 6, name: "Ahmed", age: 28 },
    { id: 7, name: "Ali", age: 25 },
    { id: 8, name: "Sara", age: 22 },
    { id: 9, name: "Ahmed", age: 28 },
    { id: 10, name: "Ali", age: 25 },
    { id: 11, name: "Sara", age: 22 },
    { id: 12, name: "Ahmed", age: 28 },
    { id: 13, name: "Ali", age: 25 },
    { id: 14, name: "Sara", age: 22 },
    { id: 15, name: "Ahmed", age: 28 }
];
export {Objectdata};